//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace WinFormTest
{
    /// <summary>
    /// 实体类CROSSDIR5MFLOWD。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_TFM_CROSSDIR_5M_FLOW")]
    [Serializable]
    public partial class CROSSDIR5MFLOWD : Entity
    {
        #region Model
        private string _ID;
        private string _SOURCE;
        private DateTime? _DATETIME;
        private double? _VOLUME;
        private double? _SPEED;
        private double? _TIMEOPY;
        private double? _HEADTIME;
        private double? _HEADDISTANCE;
        private double? _SATURATION;
        private double? _DENSITY;
        private double? _AVGLENGTH;
        private double? _VOLUME1;
        private double? _VOLUME2;
        private double? _VOLUME3;
        private double? _VOLUME4;
        private double? _VOLUME5;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public string ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SOURCE")]
        public string SOURCE
        {
            get { return _SOURCE; }
            set
            {
                this.OnPropertyValueChange("SOURCE");
                this._SOURCE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DATETIME")]
        public DateTime? DATETIME
        {
            get { return _DATETIME; }
            set
            {
                this.OnPropertyValueChange("DATETIME");
                this._DATETIME = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("VOLUME")]
        public double? VOLUME
        {
            get { return _VOLUME; }
            set
            {
                this.OnPropertyValueChange("VOLUME");
                this._VOLUME = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SPEED")]
        public double? SPEED
        {
            get { return _SPEED; }
            set
            {
                this.OnPropertyValueChange("SPEED");
                this._SPEED = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TIMEOPY")]
        public double? TIMEOPY
        {
            get { return _TIMEOPY; }
            set
            {
                this.OnPropertyValueChange("TIMEOPY");
                this._TIMEOPY = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("HEADTIME")]
        public double? HEADTIME
        {
            get { return _HEADTIME; }
            set
            {
                this.OnPropertyValueChange("HEADTIME");
                this._HEADTIME = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("HEADDISTANCE")]
        public double? HEADDISTANCE
        {
            get { return _HEADDISTANCE; }
            set
            {
                this.OnPropertyValueChange("HEADDISTANCE");
                this._HEADDISTANCE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SATURATION")]
        public double? SATURATION
        {
            get { return _SATURATION; }
            set
            {
                this.OnPropertyValueChange("SATURATION");
                this._SATURATION = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DENSITY")]
        public double? DENSITY
        {
            get { return _DENSITY; }
            set
            {
                this.OnPropertyValueChange("DENSITY");
                this._DENSITY = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AVGLENGTH")]
        public double? AVGLENGTH
        {
            get { return _AVGLENGTH; }
            set
            {
                this.OnPropertyValueChange("AVGLENGTH");
                this._AVGLENGTH = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("VOLUME1")]
        public double? VOLUME1
        {
            get { return _VOLUME1; }
            set
            {
                this.OnPropertyValueChange("VOLUME1");
                this._VOLUME1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("VOLUME2")]
        public double? VOLUME2
        {
            get { return _VOLUME2; }
            set
            {
                this.OnPropertyValueChange("VOLUME2");
                this._VOLUME2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("VOLUME3")]
        public double? VOLUME3
        {
            get { return _VOLUME3; }
            set
            {
                this.OnPropertyValueChange("VOLUME3");
                this._VOLUME3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("VOLUME4")]
        public double? VOLUME4
        {
            get { return _VOLUME4; }
            set
            {
                this.OnPropertyValueChange("VOLUME4");
                this._VOLUME4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("VOLUME5")]
        public double? VOLUME5
        {
            get { return _VOLUME5; }
            set
            {
                this.OnPropertyValueChange("VOLUME5");
                this._VOLUME5 = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.SOURCE,
                _.DATETIME,
                _.VOLUME,
                _.SPEED,
                _.TIMEOPY,
                _.HEADTIME,
                _.HEADDISTANCE,
                _.SATURATION,
                _.DENSITY,
                _.AVGLENGTH,
                _.VOLUME1,
                _.VOLUME2,
                _.VOLUME3,
                _.VOLUME4,
                _.VOLUME5,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._SOURCE,
                this._DATETIME,
                this._VOLUME,
                this._SPEED,
                this._TIMEOPY,
                this._HEADTIME,
                this._HEADDISTANCE,
                this._SATURATION,
                this._DENSITY,
                this._AVGLENGTH,
                this._VOLUME1,
                this._VOLUME2,
                this._VOLUME3,
                this._VOLUME4,
                this._VOLUME5,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "T_TFM_CROSSDIR_5M_FLOW");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SOURCE = new Field("SOURCE", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DATETIME = new Field("DATETIME", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VOLUME = new Field("VOLUME", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SPEED = new Field("SPEED", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TIMEOPY = new Field("TIMEOPY", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HEADTIME = new Field("HEADTIME", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HEADDISTANCE = new Field("HEADDISTANCE", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SATURATION = new Field("SATURATION", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DENSITY = new Field("DENSITY", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AVGLENGTH = new Field("AVGLENGTH", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VOLUME1 = new Field("VOLUME1", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VOLUME2 = new Field("VOLUME2", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VOLUME3 = new Field("VOLUME3", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VOLUME4 = new Field("VOLUME4", "T_TFM_CROSSDIR_5M_FLOW", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VOLUME5 = new Field("VOLUME5", "T_TFM_CROSSDIR_5M_FLOW", "");
        }
        #endregion
    }
}